# repos lists the config for specific repos.
repos:

- id: github.com/Nb3l77eo/testrepo

  branch: /.*/


  apply_requirements: [approved, mergeable]

  workflow: custom

  allowed_overrides: [apply_requirements, workflow, delete_source_branch_on_merge]

  allow_custom_workflows: true

  delete_source_branch_on_merge: true

workflows:
  custom:
    plan:
      steps:
      - init
      - plan:
           extra_args: ["-lock=false"]
    apply:
      steps:
      - apply